openapi: 3.0.1
info:
  title: API [TIPO-DE_API] [NOMBRE-API] V[VERSION-MAYOR]
  description: Description
  version: x.y.z
servers:
- url: [SERVER-URL-DEFINIDO-SEGUN-API]
x-bcp-api-type: [TIPO-DE_API]
x-bcp-api-id: [ID-DE-API]
externalDocs:
  url: [URL-DOCUMENTATION-SEGUN-TIPO-API]
  description: Mas informacion
tags:
- name: [NOMBRE-CONTROLADOR]
  description: [NOMBRE-CONTROLADOR] Controller
paths:
